### ISSUE TITLE
Feature Request: Attach to a process with PID

### ISSUE THREAD

**Issue by Vipul-Cariappa** [compiler-research/idd#28]
We currently only support debugging by launching the program.
We should also consider attaching to a running process.

My personal simplified use case:
while debugging cppyy. I have the following code setup.
```python
import os
print(os.getpid())
import cppyy

cppyy.cppdef("""
// code to compile
""")

# any additional setup code

breakpoint() # drops me to python debugger, then I attach gdb to this process and continue execution

# code used to debug
```

**Comment by vgvassilev** [comment]
Essentially having a -p flag to gdb.
